name: Docker Image CI

on:
  push:
    branches: [ master ]
    
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: bash ./docker-build.sh 

    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        username: cdecl
        password: ${{ secrets.SECRET_KEY }}
        
    - name: Push Docker image
      run: docker push cdecl/rclone:latest
